import { Amplify } from 'aws-amplify';

/**
 * Configure Amplify with the outputs from the backend deployment.
 *
 * For local development: Run `npx ampx sandbox` to generate amplify_outputs.json
 * For production: Amplify Hosting automatically generates this file during deployment
 */
export async function configureAmplify(): Promise<void> {
  try {
    // Fetch the config file from public directory
    // The file is generated by Amplify sandbox (local) or Amplify Hosting (production)
    const response = await fetch('/amplify_outputs.json');
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }
    const outputs = await response.json();
    Amplify.configure(outputs);
    console.log('Amplify configured successfully');
  } catch (error) {
    console.error('Failed to configure Amplify:', error);
    throw new Error(
      'Failed to load Amplify configuration. Run `npx ampx sandbox` to generate amplify_outputs.json for local development.'
    );
  }
}
